version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    env_file:
      - influxdb.env
    volumes:
      - influxdb-docker-data-volume:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

volumes:
  influxdb-docker-data-volume: